export class AndroidOrmLiteJavaMapping {
    public static dataTypeMapping: { [mappings: string]: { [dbtype: string]: string } } = {
        "Java": {
            tinyint: "Integer",
            boolean: "Boolean",
            smallint: "Integer",
            int: "Integer",
            integer: "Integer",
            mediumint: "Integer",
            bigint: "java.math.BigInteger",
            year: "Integer",
            float: "Integer",
            double: "Double",
            decimal: "Double",
            "double precision": "Double",
            real: "Double",
            numeric: "Double",
            money: "Double",
            timestamp: "java.util.Date",
            date: "java.util.Date",
            datetime: "java.util.Date",
            datetime2: "java.util.Date",
            tinyblob: "byte[]",
            mediumblob: "byte[]",
            longblob: "byte[]",
            blob: "byte[]",
            image: "byte[]",
            binary: "byte[]",
            varbinary: "byte[]",
            bit: "Boolean",
            bytea: "byte[]",
            char: "String",
            nchar: "String",
            character: "String",
            varchar: "String",
            nvarchar: "String",
            tinytext: "String",
            mediumtext: "String",
            longtext: "String",
            text: "String",
            ntext: "String",
            "enum": "String",
            "set": "String",
            time: "String",
            geometry: "String",
            "character varying": "String",
            "USER-DEFINED": "String",
            "uniqueidentifier": "java.util.UUID"
        },
        "OrmliteColumnFormat": {
            tinyint: <any>null,
            boolean: <any>null,
            smallint: <any>null,
            int: <any>null,
            integer: <any>null,
            mediumint: <any>null,
            bigint: <any>null,
            year: <any>null,
            float: <any>null,
            double: <any>null,
            decimal: <any>null,
            "double precision": <any>null,
            real: <any>null,
            numeric: <any>null,
            money: <any>null,
            timestamp: 'yyyy-MM-dd HH:mm:ss.SSSSSS',
            date: 'yyyy-MM-dd',
            datetime: 'yyyy-MM-dd HH:mm',
            datetime2: 'yyyy-MM-dd HH:mm',
            tinyblob: <any>null,
            mediumblob: <any>null,
            longblob: <any>null,
            blob: <any>null,
            image: <any>null,
            binary: <any>null,
            varbinary: <any>null,
            bit: <any>null,
            bytea: <any>null,
            char: <any>null,
            nchar: <any>null,
            varchar: <any>null,
            nvarchar: <any>null,
            tinytext: <any>null,
            mediumtext: <any>null,
            longtext: <any>null,
            text: <any>null,
            ntext: <any>null,
            "enum": <any>null,
            "set": <any>null,
            time: <any>null,
            geometry: <any>null,
            "character varying": <any>null,
            character: <any>null,
            "USER-DEFINED": <any>null,
            uniqueidentifier: <any>null,
        },
        "OrmliteColumnFormatUTC": {
            tinyint: <any>null,
            boolean: <any>null,
            smallint: <any>null,
            int: <any>null,
            integer: <any>null,
            mediumint: <any>null,
            bigint: <any>null,
            year: <any>null,
            float: <any>null,
            double: <any>null,
            decimal: <any>null,
            "double precision": <any>null,
            real: <any>null,
            numeric: <any>null,
            money: <any>null,
            timestamp: 'yyyy-MM-dd HH:mm:ss.SSSSSS Z',
            date: 'yyyy-MM-dd Z',
            datetime: 'yyyy-MM-dd HH:mm Z',
            datetime2: 'yyyy-MM-dd HH:mm Z',
            tinyblob: <any>null,
            mediumblob: <any>null,
            longblob: <any>null,
            blob: <any>null,
            image: <any>null,
            binary: <any>null,
            varbinary: <any>null,
            bit: <any>null,
            bytea: <any>null,
            char: <any>null,
            nchar: <any>null,
            varchar: <any>null,
            nvarchar: <any>null,
            tinytext: <any>null,
            mediumtext: <any>null,
            longtext: <any>null,
            time: <any>null,
            text: <any>null,
            ntext: <any>null,
            "enum": <any>null,
            "set": <any>null,
            geometry: <any>null,
            "character varying": <any>null,
            character: <any>null,
            "USER-DEFINED": <any>null,
            uniqueidentifier: <any>null,
        },
        "OrmliteDataType": {
            tinyint: <any>null,
            boolean: <any>null,
            smallint: <any>null,
            int: <any>null,
            integer: <any>null,
            mediumint: <any>null,
            bigint: <any>null,
            year: <any>null,
            float: <any>null,
            double: <any>null,
            decimal: <any>null,
            "double precision": <any>null,
            real: <any>null,
            numeric: <any>null,
            money: <any>null,
            timestamp: 'com.j256.ormlite.field.DataType.DATE_STRING',
            date: 'com.j256.ormlite.field.DataType.DATE_STRING',
            datetime: 'com.j256.ormlite.field.DataType.DATE_STRING',
            datetime2: 'com.j256.ormlite.field.DataType.DATE_STRING',
            tinyblob: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            mediumblob: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            longblob: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            blob: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            image: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            binary: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            varbinary: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            bit: <any>null,
            bytea: 'com.j256.ormlite.field.DataType.BYTE_ARRAY',
            char: <any>null,
            nchar: <any>null,
            varchar: <any>null,
            nvarchar: <any>null,
            tinytext: <any>null,
            mediumtext: <any>null,
            longtext: <any>null,
            text: <any>null,
            ntext: <any>null,
            "enum": <any>null,
            "set": <any>null,
            time: <any>null,
            geometry: <any>null,
            "character varying": <any>null,
            character: <any>null,
            "USER-DEFINED": <any>null,
            uniqueidentifier: <any>null,
        }
    }
}
